import { Channel, Message, Note, Project, SharedFile, Todo, User } from '@/types'

export const MOCK_USER: User = {
  id: 'user-1',
  email: 'you@flowspace.app',
  name: 'You',
  avatar_url: undefined,
  created_at: new Date().toISOString(),
}

export const MOCK_TEAM: User[] = [
  { id: 'user-2', email: 'alex@team.com', name: 'Alex Chen', created_at: new Date().toISOString() },
  { id: 'user-3', email: 'sam@team.com', name: 'Sam Rivera', created_at: new Date().toISOString() },
  { id: 'user-4', email: 'jordan@team.com', name: 'Jordan Kim', created_at: new Date().toISOString() },
]

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the marketing site',
    color: '#6366f1',
    emoji: '🎨',
    owner_id: 'user-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    _count: { todos: 12, notes: 5, files: 8 },
  },
  {
    id: 'proj-2',
    name: 'Mobile App v2',
    description: 'New features for the mobile app',
    color: '#8b5cf6',
    emoji: '📱',
    owner_id: 'user-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    _count: { todos: 7, notes: 3, files: 4 },
  },
  {
    id: 'proj-3',
    name: 'API Integration',
    description: 'Third-party service integrations',
    color: '#14b8a6',
    emoji: '🔌',
    owner_id: 'user-2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    _count: { todos: 5, notes: 2, files: 6 },
  },
]

export const MOCK_TODOS: Todo[] = [
  {
    id: 'todo-1',
    title: 'Design new landing page hero',
    description: 'Create a compelling hero section with animation',
    status: 'in_progress',
    priority: 'high',
    project_id: 'proj-1',
    assignee_id: 'user-1',
    due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'user-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    order: 0,
    labels: ['design', 'frontend'],
  },
  {
    id: 'todo-2',
    title: 'Set up authentication flow',
    status: 'todo',
    priority: 'urgent',
    project_id: 'proj-1',
    assignee_id: 'user-2',
    due_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'user-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    order: 0,
    labels: ['backend', 'security'],
  },
  {
    id: 'todo-3',
    title: 'Write API documentation',
    status: 'backlog',
    priority: 'medium',
    project_id: 'proj-3',
    created_by: 'user-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    order: 0,
    labels: ['docs'],
  },
  {
    id: 'todo-4',
    title: 'Fix mobile nav responsiveness',
    status: 'done',
    priority: 'low',
    project_id: 'proj-1',
    assignee_id: 'user-3',
    created_by: 'user-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    order: 0,
    labels: ['frontend', 'bug'],
  },
  {
    id: 'todo-5',
    title: 'Implement push notifications',
    status: 'todo',
    priority: 'medium',
    project_id: 'proj-2',
    assignee_id: 'user-1',
    created_by: 'user-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    order: 1,
    labels: ['mobile'],
  },
  {
    id: 'todo-6',
    title: 'Performance audit & optimization',
    status: 'backlog',
    priority: 'high',
    project_id: 'proj-1',
    created_by: 'user-2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    order: 1,
    labels: ['performance'],
  },
]

export const MOCK_NOTES: Note[] = [
  {
    id: 'note-1',
    title: 'Project Kickoff Notes',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Project Kickoff' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Key decisions made during the kickoff meeting...' }] },
      ],
    }),
    project_id: 'proj-1',
    created_by: 'user-1',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    is_pinned: true,
  },
  {
    id: 'note-2',
    title: 'API Design Decisions',
    content: JSON.stringify({ type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'REST vs GraphQL considerations...' }] }] }),
    project_id: 'proj-3',
    created_by: 'user-2',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    is_pinned: false,
  },
  {
    id: 'note-3',
    title: 'Design System Guidelines',
    content: JSON.stringify({ type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Color palette, typography, and component rules...' }] }] }),
    project_id: 'proj-1',
    created_by: 'user-1',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    is_pinned: false,
  },
]

export const MOCK_CHANNELS: Channel[] = [
  { id: 'ch-1', name: 'general', is_dm: false, created_at: new Date().toISOString(), unread_count: 3 },
  { id: 'ch-2', name: 'design', is_dm: false, created_at: new Date().toISOString(), project_id: 'proj-1', unread_count: 0 },
  { id: 'ch-3', name: 'dev', is_dm: false, created_at: new Date().toISOString(), project_id: 'proj-1', unread_count: 1 },
  { id: 'ch-4', name: 'Alex Chen', is_dm: true, dm_users: ['user-1', 'user-2'], created_at: new Date().toISOString(), unread_count: 2 },
  { id: 'ch-5', name: 'Sam Rivera', is_dm: true, dm_users: ['user-1', 'user-3'], created_at: new Date().toISOString(), unread_count: 0 },
]

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    channel_id: 'ch-1',
    content: "Hey team! Just pushed the latest design updates. Check out the Figma link 🎨",
    user_id: 'user-2',
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    is_edited: false,
    reactions: [{ emoji: '👍', user_ids: ['user-1', 'user-3'] }, { emoji: '🔥', user_ids: ['user-1'] }],
  },
  {
    id: 'msg-2',
    channel_id: 'ch-1',
    content: "Looks great! The color palette is much better now. I especially like the new hero section.",
    user_id: 'user-3',
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    is_edited: false,
  },
  {
    id: 'msg-3',
    channel_id: 'ch-1',
    content: "Agreed! Should we schedule a review call tomorrow to go over the full flow?",
    user_id: 'user-1',
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    is_edited: false,
    reactions: [{ emoji: '✅', user_ids: ['user-2', 'user-3', 'user-4'] }],
  },
]

export const MOCK_FILES: SharedFile[] = [
  {
    id: 'file-1',
    name: 'design-system.fig',
    size: 2400000,
    type: 'application/figma',
    url: '#',
    project_id: 'proj-1',
    uploaded_by: 'user-2',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    is_code: false,
  },
  {
    id: 'file-2',
    name: 'api-config.ts',
    size: 3200,
    type: 'text/typescript',
    url: '#',
    project_id: 'proj-3',
    uploaded_by: 'user-1',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    is_code: true,
    language: 'typescript',
    content: `import axios from 'axios'\n\nexport const api = axios.create({\n  baseURL: process.env.NEXT_PUBLIC_API_URL,\n  timeout: 10000,\n  headers: {\n    'Content-Type': 'application/json',\n  },\n})\n\napi.interceptors.request.use((config) => {\n  const token = localStorage.getItem('token')\n  if (token) config.headers.Authorization = \`Bearer \${token}\`\n  return config\n})`,
  },
  {
    id: 'file-3',
    name: 'brand-assets.zip',
    size: 15600000,
    type: 'application/zip',
    url: '#',
    project_id: 'proj-1',
    uploaded_by: 'user-2',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    is_code: false,
  },
  {
    id: 'file-4',
    name: 'database-schema.sql',
    size: 8900,
    type: 'text/sql',
    url: '#',
    project_id: 'proj-3',
    uploaded_by: 'user-3',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    is_code: true,
    language: 'sql',
    content: `CREATE TABLE users (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  email TEXT UNIQUE NOT NULL,\n  name TEXT NOT NULL,\n  created_at TIMESTAMPTZ DEFAULT NOW()\n);\n\nCREATE TABLE projects (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  name TEXT NOT NULL,\n  owner_id UUID REFERENCES users(id),\n  created_at TIMESTAMPTZ DEFAULT NOW()\n);`,
  },
]
